/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpg_game;
import java.util.Scanner;

public class App {

    Player player = new Player();
    Dungeon dungeon = new Dungeon();
    Town town = new Town();
    private Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        App app = new App();
        app.welcomeTraveler();
        // app.askForName();
        // app.askForRole();
        // While end boss isn't defeated
        while(true) {
            if (app.player.getIsAlive()){

                app.player.revive();
            }
            app.player.showOptions();
            app.askTravelChoice();
        }

    }

    private void askTravelChoice(){
        System.out.println("Would you like to go to the dungeon(0) or into town(1)?");
        System.out.println(player.armor.getArmorScore());
        int travelChoice = scanner.nextInt();
        if(travelChoice == 0){
           dungeon.enter(player);
        }else{
            town.enter(player);
        }
    }
    private void welcomeTraveler(){
        System.out.println("Welcome traveler. What is your name?");
    }
    private void askForName(){
        String name = scanner.nextLine();
        player.setName(name);
        System.out.println("Grettings " + player.getName());
    }
        
    // private void askForRole(){
    //     System.out.println("What is your role?");
    //     System.out.println("Available Roles: 'Barbarian, Mage, Rouge'");
    //     String role = scanner.nextLine();
    //     player.setRole(role);
        
    //     System.out.println("So You're a " + player.getRole() + ", huh? Interesting");
    // }
}
